#!/bin/sh

if [ $# -ne 22 ]; then
    echo 1>&2 Usage: $0 expected 22 arguments
    exit 127
fi

TARGET=${1}
VALUE=${2}
DURATION=${3}
CURRENT_VALUE=${4}

APP1_CPU_PID=${5}
APP1_CPU_NAME=${6}
APP1_CPU_VALUE=${7}

APP2_CPU_PID=${8}
APP2_CPU_NAME=${9}
APP2_CPU_VALUE=${10}

APP3_CPU_PID=${11}
APP3_CPU_NAME=${12}
APP3_CPU_VALUE=${13}

APP1_RAM_PID=${14}
APP1_RAM_NAME=${15}
APP1_RAM_VALUE=${16}

APP2_RAM_PID=${17}
APP2_RAM_NAME=${18}
APP2_RAM_VALUE=${19}

APP3_RAM_PID=${20}
APP3_RAM_NAME=${21}
APP3_RAM_VALUE=${22}

echo 1>&2 TARGET=$TARGET VALUE=$VALUE DURATION=$DURATION CURRENT_VALUE=$CURRENT_VALUE

echo 1>&2 APP1_CPU_PID=$APP1_CPU_PID APP1_CPU_NAME=$APP1_CPU_NAME APP1_CPU_VALUE=$APP1_CPU_VALUE
echo 1>&2 APP2_CPU_PID=$APP2_CPU_PID APP2_CPU_NAME=$APP2_CPU_NAME APP2_CPU_VALUE=$APP2_CPU_VALUE
echo 1>&2 APP3_CPU_PID=$APP3_CPU_PID APP3_CPU_NAME=$APP3_CPU_NAME APP3_CPU_VALUE=$APP3_CPU_VALUE

echo 1>&2 APP1_RAM_PID=$APP1_RAM_PID APP1_RAM_NAME=$APP1_RAM_NAME APP1_RAM_VALUE=$APP1_RAM_VALUE
echo 1>&2 APP2_RAM_PID=$APP2_RAM_PID APP2_RAM_NAME=$APP2_RAM_NAME APP2_RAM_VALUE=$APP2_RAM_VALUE
echo 1>&2 APP3_RAM_PID=$APP3_RAM_PID APP3_RAM_NAME=$APP3_RAM_NAME APP3_RAM_VALUE=$APP3_RAM_VALUE

exit 0
